## **Essential Python for Data Analyst**

- Review `Class`
- try except
- csv file, context manager
- pip install packages
- pandas & numpy
- web scraping `gazpacho`
- API `requests`
- Basic ML `sklearn`

In [ ]:
# OOP object 
class Person:
    def __init__(self, name, age):
        self.name = name
        self.age = age
    
    def say_hi(self):
        print("hello!")

    def __str__(self):
        return "I am a person. My name is " + self.name + '.'

In [ ]:
john = Person("John", 25)

print(john)

I am a person. My name is John.


In [ ]:
# OOP inheritance
# Employee <- Person

class Employee(Person):
    def __init__(self, name, age, position, company):
        super().__init__(name, age)
        self.position = position
        self.company = company
    
    def say_hi(self):
        print(f"Hello! I'm {self.name}.")

    def killing(self):
        print("Yeah!")

In [ ]:
john_wick = Employee("John Wick", 35, "Assasin", "Twitter")

In [ ]:
print(john_wick.name)
print(john_wick.age)
print(john_wick.position)
print(john_wick.company)

John Wick
35
Assasin
Twitter


In [ ]:
type(john_wick)

__main__.Employee

In [ ]:
john_wick.say_hi()

Hello! I'm John Wick.


In [ ]:
john_wick.killing() # function

Yeah!


In [ ]:
john_wick.company # variable

'Twitter'

## Run Command Line in Notebook

In [ ]:
!pwd

/content


In [ ]:
!ls

sample_data


In [ ]:
!mkdir data

In [ ]:
!ls data

 chinook.db   food.txt	 hotel.csv  'Sample SuperStore.csv'


In [ ]:
!cat data/food.txt

hamburger
hotdog
pizza
salad
french fried

In [ ]:
!pip install gazpacho

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Created wheel for gazpacho: filename=gazpacho-1.1-py3-none-any.whl size=7482 sha256=b674f57b7d94616c051ff5755a22d031f2b3cbd809bc119a9851ae7c029a0590
  Stored in directory: /root/.cache/pip/wheels/ec/45/e0/490eb5e25601b4f9425fcde4a0034601c492a29e82268be4d3
Successfully built gazpacho


In [ ]:
!pip list | grep "^gaz"

gazpacho                      1.1


In [ ]:
# import package/ library/ module
import csv

In [ ]:
!ls data

 chinook.db   food.txt	 hotel.csv  'Sample SuperStore.csv'


In [ ]:
file = open("data/hotel.csv")

data = []

content = csv.reader(file)

for row in content:
    data.append(row)

file.close()

print(data)

[['id', 'hotel', 'location', 'pricepernight'], ['1', 'Ideo', 'Bangkok', '20'], ['2', 'Accor', 'London', '25'], ['3', 'Premium', 'Seoul', '32'], ['4', 'Super Star', 'Dubai', '50'], ['5', 'Planet', 'Tokyo', '22'], ['6', 'Joby', 'Bangkok', '30'], ['7', 'JW Marriot', 'Bangkok', '35'], ['8', 'Kenshin', 'Tokyo', '20'], ['9', 'Eloquent', 'London', '42'], ['10', 'Big Ben', 'London', '45']]


In [ ]:
# context manager read/write file

In [ ]:
data = []

with open("data/hotel.csv", "r") as file:
    content = csv.reader(file)
    for row in content:
        data.append(row)

print(data)

[['id', 'hotel', 'location', 'pricepernight'], ['1', 'Ideo', 'Bangkok', '20'], ['2', 'Accor', 'London', '25'], ['3', 'Premium', 'Seoul', '32'], ['4', 'Super Star', 'Dubai', '50'], ['5', 'Planet', 'Tokyo', '22'], ['6', 'Joby', 'Bangkok', '30'], ['7', 'JW Marriot', 'Bangkok', '35'], ['8', 'Kenshin', 'Tokyo', '20'], ['9', 'Eloquent', 'London', '42'], ['10', 'Big Ben', 'London', '45']]


In [ ]:
# write file data.txt

header = ['id', 'name', 'city']
body_data = [
    [1, 'John', 'London'], 
    [2, 'Mary', 'Reading'],
    [3, 'Anna', 'Belgium']
]

with open("data/output.csv", "w") as file:
    writer = csv.writer(file)
    writer.writerow(header)
    writer.writerows(body_data)

In [ ]:
!ls data

 chinook.db   food.txt	 hotel.csv   output.csv  'Sample SuperStore.csv'


In [ ]:
!cat data/output.csv

id,name,city
1,John,London
2,Mary,Reading
3,Anna,Belgium


In [ ]:
# How to handle error

In [ ]:
# try - except block

In [ ]:
try:
    print(1/0)
    print("Success!")
except ZeroDivisionError:
    print("this code is error!")
except NameError:
    print("variable not found!")
finally:
    print("Done...")

this code is error!
Done...


In [ ]:
try:
    with open("data/HOTEL.csv", "r") as file:
        data = csv.reader(file)
        for row in data:
            print(row)
    print("Load data successfully!")
except FileNotFoundError:
    print("File not found. Please check file name again.")

File not found. Please check file name again.


## CSVMonster Class

In [ ]:
class CSVMonster:
    def __init__(self, filename):
        self.data = [] # list
        try:
            with open(filename, "r") as file:
                content = csv.reader(file)
                for row in content:
                    self.data.append(row)
            print("Load data successfully.")
        except FileNotFoundError:
            print("Error. Please check file name again.")

    def info(self):
        columns = len(self.data[0])
        rows = len(self.data) - 1
        print(f"Columns: {columns}\nRows: {rows}")

    def filter_city(self, city):
        header = self.data[0]
        data = self.data[1:]
        result = []

        for row in data:
            if row[2] == city:
                result.append(row)
        
        print(header)
        for row in result:
            print(row)
    
    def calculate_avg_price(self):
        prices = []
        for row in self.data[1:]: # no use head 
            prices.append(int(row[3]))  # name head row

        avg_price = sum(prices) / len(prices)
        print(f"Avg. Price: {avg_price}")


In [ ]:
csv_file = CSVMonster("data/hotel.csv")

Load data successfully.


In [ ]:
csv_file.info()

Columns: 4
Rows: 10


In [ ]:
csv_file.filter_city("London")

['id', 'hotel', 'location', 'pricepernight']
['2', 'Accor', 'London', '25']
['9', 'Eloquent', 'London', '42']
['10', 'Big Ben', 'London', '45']


In [ ]:
csv_file.calculate_avg_price()

Avg. Price: 32.1


## **Intro to Numpy**

Numpy = numerical python

In [ ]:
values = [1,2,3,4,5]
print(values * 2)

print(values + values + values)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [ ]:
[value*2  for value in values]

# value * 2

[2, 4, 6, 8, 10]

In [ ]:
import numpy as np

values = [1,2,3,4,5]
np_values = np.array(values)

print(type(values), type(np_values))

<class 'list'> <class 'numpy.ndarray'>


In [ ]:
np_values ** 3

array([  1,   8,  27,  64, 125])

In [ ]:
ages = np.array([25, 28, 30, 19, 32])

print(ages.mean())
print(ages.sum())
print(ages.min())
print(ages.max())
print(ages.std())

26.8
134
19
32
4.534313619501853


In [ ]:
np.std(ages)

4.534313619501853

In [ ]:
# dot notation
# multiplication
np.dot(3, 5)

15

In [ ]:
a1 = np.array([1,2,3])
a2 = np.array([2,5,2])

# =SUMPRODUCT()
# = (1*2) + (2*5) + (3*2)
np.dot(a1, a2)

18

In [ ]:
# matrix
a1 = np.array([
    [1,2],
    [3,4]
])

a2 = np.array([
    [5,6],
    [2,5]
])

# sum((1,2) * (6,5))
np.dot(a1, a2)

array([[ 9, 16],
       [23, 38]])

In [ ]:
# start stop step
np.arange(1, 101,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [ ]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## **Intro to Pandas**

- information of data frame
- select columns
- filter rows
- create new column
- aggregate + summarise
- value counts

In [ ]:
import pandas as pd 
import numpy as np 

In [ ]:
# load csv data
df = pd.read_csv("data/store.csv")

In [ ]:
# preview dataset
df.tail(3)

Row ID        Order ID Order Date Ship Date       Ship Mode Customer ID  \
9991    9992  CA-2017-121258  2/26/2017  3/3/2017  Standard Class    DB-13060   
9992    9993  CA-2017-121258  2/26/2017  3/3/2017  Standard Class    DB-13060   
9993    9994  CA-2017-119914   5/4/2017  5/9/2017    Second Class    CC-12220   

     Customer Name   Segment        Country         City  ... Postal Code  \
9991   Dave Brooks  Consumer  United States   Costa Mesa  ...       92627   
9992   Dave Brooks  Consumer  United States   Costa Mesa  ...       92627   
9993  Chris Cortes  Consumer  United States  Westminster  ...       92683   

      Region       Product ID         Category Sub-Category  \
9991    West  TEC-PH-10003645       Technology       Phones   
9992    West  OFF-PA-10004041  Office Supplies        Paper   
9993    West  OFF-AP-10002684  Office Supplies   Appliances   

                                           Product Name    Sales  Quantity  \
9991                              Aastra 57i VoIP phone  258.576         2   
9992  It's Hot Message Books with Stickers, 2 3/4" x 5"   29.600         4   
9993  Acco 7-Outlet Masterpiece Power Center, Wihtou...  243.160         2   

      Discount   Profit  
9991       0.2  19.3932  
9992       0.0  13.3200  
9993       0.0  72.9480  

[3 rows x 21 columns]

In [ ]:
# information of data
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Row ID         9994 non-null   int64  
 1   Order ID       9994 non-null   object 
 2   Order Date     9994 non-null   object 
 3   Ship Date      9994 non-null   object 
 4   Ship Mode      9994 non-null   object 
 5   Customer ID    9994 non-null   object 
 6   Customer Name  9994 non-null   object 
 7   Segment        9994 non-null   object 
 8   Country        9994 non-null   object 
 9   City           9994 non-null   object 
 10  State          9994 non-null   object 
 11  Postal Code    9994 non-null   int64  
 12  Region         9994 non-null   object 
 13  Product ID     9994 non-null   object 
 14  Category       9994 non-null   object 
 15  Sub-Category   9994 non-null   object 
 16  Product Name   9994 non-null   object 
 17  Sales          9994 non-null   float64
 18  Quantity

In [ ]:
df.shape # attribute

(9994, 21)

In [ ]:
df.describe()

Row ID   Postal Code         Sales     Quantity     Discount  \
count  9994.000000   9994.000000   9994.000000  9994.000000  9994.000000   
mean   4997.500000  55190.379428    229.858001     3.789574     0.156203   
std    2885.163629  32063.693350    623.245101     2.225110     0.206452   
min       1.000000   1040.000000      0.444000     1.000000     0.000000   
25%    2499.250000  23223.000000     17.280000     2.000000     0.000000   
50%    4997.500000  56430.500000     54.490000     3.000000     0.200000   
75%    7495.750000  90008.000000    209.940000     5.000000     0.200000   
max    9994.000000  99301.000000  22638.480000    14.000000     0.800000   

            Profit  
count  9994.000000  
mean     28.656896  
std     234.260108  
min   -6599.978000  
25%       1.728750  
50%       8.666500  
75%      29.364000  
max    8399.976000

In [ ]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')

In [ ]:
# clean column names
cols = df.columns 
clean_cols = [col.lower().replace(" ", "_").replace("-","_")  for col in cols]
df.columns = clean_cols

df.head(1)

row_id        order_id order_date   ship_date     ship_mode customer_id  \
0       1  CA-2016-152156  11/8/2016  11/11/2016  Second Class    CG-12520   

  customer_name   segment        country       city  ... postal_code  region  \
0   Claire Gute  Consumer  United States  Henderson  ...       42420   South   

        product_id   category sub_category                       product_name  \
0  FUR-BO-10001798  Furniture    Bookcases  Bush Somerset Collection Bookcase   

    sales  quantity  discount   profit  
0  261.96         2       0.0  41.9136  

[1 rows x 21 columns]

In [ ]:
# select columns
df['segment'].head()

0     Consumer
1     Consumer
2    Corporate
3     Consumer
4     Consumer
Name: segment, dtype: object

In [ ]:
# create new column
selected_cols = ['order_id', 'segment', 'sales', 'state', 'city']

df2 = df[selected_cols]

df2['tax'] = df2['sales'] * 0.25

df2.head(3)

<ipython-input-53-89565a0c35e7>:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['tax'] = df2['sales'] * 0.25


order_id    segment   sales       state         city      tax
0  CA-2016-152156   Consumer  261.96    Kentucky    Henderson   65.490
1  CA-2016-152156   Consumer  731.94    Kentucky    Henderson  182.985
2  CA-2016-138688  Corporate   14.62  California  Los Angeles    3.655

In [ ]:
# remove columns
df2 = df2.drop(['order_id','city'], axis=1)
df2.head()

segment     sales       state         tax
0   Consumer  261.9600    Kentucky   65.490000
1   Consumer  731.9400    Kentucky  182.985000
2  Corporate   14.6200  California    3.655000
3   Consumer  957.5775     Florida  239.394375
4   Consumer   22.3680     Florida    5.592000

In [ ]:
# filter data
df[ (df['category'] == 'Furniture') & (df['segment'] == 'Home Office') ][['customer_name', 'segment', 'category']].head(20)

customer_name      segment   category
38         Steve Nguyen  Home Office  Furniture
39         Steve Nguyen  Home Office  Furniture
66       Paul Stevenson  Home Office  Furniture
96       Parhena Norris  Home Office  Furniture
124      Alan Dominguez  Home Office  Furniture
128    Lindsay Shagiari  Home Office  Furniture
129    Lindsay Shagiari  Home Office  Furniture
146   Maureen Gastineau  Home Office  Furniture
189         Mark Packer  Home Office  Furniture
192         Mark Packer  Home Office  Furniture
231  Christopher Schild  Home Office  Furniture
232  Christopher Schild  Home Office  Furniture
234  Christopher Schild  Home Office  Furniture
244       Dianna Wilson  Home Office  Furniture
292       Nick Zandusky  Home Office  Furniture
317        Nathan Mautz  Home Office  Furniture
462       Tanja Norvell  Home Office  Furniture
463       Tanja Norvell  Home Office  Furniture
467     Joni Sundaresam  Home Office  Furniture
485       Michelle Tran  Home Office  Furniture

In [ ]:
# query() method
result = df.query("category == 'Furniture' and segment == 'Consumer' ")[['customer_name', 'segment', 'category']].tail(10)

result

customer_name   segment   category
9897         Liz Preis  Consumer  Furniture
9898         Liz Preis  Consumer  Furniture
9901        Sung Chung  Consumer  Furniture
9903     Darren Powers  Consumer  Furniture
9917    Tamara Manning  Consumer  Furniture
9928     Ionia McGrath  Consumer  Furniture
9931     Keith Herrera  Consumer  Furniture
9980       Shaun Weien  Consumer  Furniture
9989  Tom Boeckenhauer  Consumer  Furniture
9990       Dave Brooks  Consumer  Furniture

In [ ]:
# export csv file
result.to_csv("data/output_store.csv")

In [ ]:
!ls data

chinook.db  food.txt  hotel.csv  output.csv  output_store.csv  store.csv


In [ ]:
# value counts
count_segment = df['segment'].value_counts(normalize=True).reset_index()
count_segment.to_csv("data/segment.csv")

count_segment

index   segment
0     Consumer  0.519412
1    Corporate  0.302181
2  Home Office  0.178407

In [ ]:
# statistics (aggregate functions)
# numpy statistics
total_sales = df['sales'].sum()
avg_sales = df['sales'].mean() 
std_quantity = df['quantity'].std()

print(f"Total Sales: {round(total_sales,2)}")
print(avg_sales, std_quantity)

Total Sales: 2297200.86
229.85800083049833 2.2251096911414


In [ ]:
median_sales = np.median(df['sales'])
print(median_sales)

54.489999999999995


In [ ]:
# groupby + aggregate
df.groupby('segment')['sales'].agg(['sum', 'mean', 'count', 'min', 'max'])

sum        mean  count    min       max
segment                                                      
Consumer     1.161401e+06  223.733644   5191  0.444  13999.96
Corporate    7.061464e+05  233.823300   3020  0.556  17499.95
Home Office  4.296531e+05  240.972041   1783  0.990  22638.48

In [ ]:
result = df.groupby(['state','segment'])[['sales', 'profit']]\
    .agg(['sum','mean'])\
    .reset_index()

result.head()
# result.to_csv("data/request_data_18Nov2022.csv")

state      segment      sales                 profit            
                               sum        mean        sum        mean
0  Alabama     Consumer   7537.540  301.501600  1711.0939   68.443756
1  Alabama    Corporate  10969.380  391.763571  3648.3846  130.299450
2  Alabama  Home Office   1003.720  125.465000   427.3468   53.418350
3  Arizona     Consumer  16424.422  149.312927 -1423.0527  -12.936843
4  Arizona    Corporate  11736.322  170.091623  -788.9158  -11.433562

In [ ]:
# OKAY : )

## **API**

API => Application Programming Interface

Request-Response cycle

import `requests`

In [ ]:
import requests 
import time
import pandas as pd 

In [ ]:
url ="https://swapi.dev/api/people/1"

In [ ]:
response = requests.get(url)

In [ ]:
response.status_code

200

In [ ]:
result = response.json()

In [ ]:
result['height']

'172'

In [ ]:
result['mass']

'77'

In [ ]:
result

{'name': 'Luke Skywalker',
 'height': '172',
 'mass': '77',
 'hair_color': 'blond',
 'skin_color': 'fair',
 'eye_color': 'blue',
 'birth_year': '19BBY',
 'gender': 'male',
 'homeworld': 'https://swapi.dev/api/planets/1/',
 'films': ['https://swapi.dev/api/films/1/',
  'https://swapi.dev/api/films/2/',
  'https://swapi.dev/api/films/3/',
  'https://swapi.dev/api/films/6/'],
 'species': [],
 'vehicles': ['https://swapi.dev/api/vehicles/14/',
  'https://swapi.dev/api/vehicles/30/'],
 'starships': ['https://swapi.dev/api/starships/12/',
  'https://swapi.dev/api/starships/22/'],
 'created': '2014-12-09T13:50:51.644000Z',
 'edited': '2014-12-20T21:17:56.891000Z',
 'url': 'https://swapi.dev/api/people/1/'}

In [ ]:
names = []
heights = []
masses = []

for i in range(1,11):
    url = f"https://swapi.dev/api/people/{i}"
    resp = requests.get(url)
    result = resp.json()
    names.append(result['name'])
    heights.append(result['height'])
    masses.append(result['mass'])
    time.sleep(1)

df = pd.DataFrame({
    "name": names, "height": heights, "mass": masses
})

df

name height mass
0      Luke Skywalker    172   77
1               C-3PO    167   75
2               R2-D2     96   32
3         Darth Vader    202  136
4         Leia Organa    150   49
5           Owen Lars    178  120
6  Beru Whitesun lars    165   75
7               R5-D4     97   32
8   Biggs Darklighter    183   84
9      Obi-Wan Kenobi    182   77

In [ ]:
result # dictionary

{'name': 'Obi-Wan Kenobi',
 'height': '182',
 'mass': '77',
 'hair_color': 'auburn, white',
 'skin_color': 'fair',
 'eye_color': 'blue-gray',
 'birth_year': '57BBY',
 'gender': 'male',
 'homeworld': 'https://swapi.dev/api/planets/20/',
 'films': ['https://swapi.dev/api/films/1/',
  'https://swapi.dev/api/films/2/',
  'https://swapi.dev/api/films/3/',
  'https://swapi.dev/api/films/4/',
  'https://swapi.dev/api/films/5/',
  'https://swapi.dev/api/films/6/'],
 'species': [],
 'vehicles': ['https://swapi.dev/api/vehicles/38/'],
 'starships': ['https://swapi.dev/api/starships/48/',
  'https://swapi.dev/api/starships/59/',
  'https://swapi.dev/api/starships/64/',
  'https://swapi.dev/api/starships/65/',
  'https://swapi.dev/api/starships/74/'],
 'created': '2014-12-10T16:16:29.192000Z',
 'edited': '2014-12-20T21:17:50.325000Z',
 'url': 'https://swapi.dev/api/people/10/'}

## **Web Scraping**

In [ ]:
!pip install gazpacho

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Created wheel for gazpacho: filename=gazpacho-1.1-py3-none-any.whl size=7482 sha256=31c9f7ca5b269e819190f9c1b9c1a427c3a5ba3dabd5d5c6d44008510c838017
  Stored in directory: /root/.cache/pip/wheels/ec/45/e0/490eb5e25601b4f9425fcde4a0034601c492a29e82268be4d3
Successfully built gazpacho


In [ ]:
from gazpacho import Soup
from requests import get

In [ ]:
url = "https://www.imdb.com/search/title/?groups=top_100&sort=user_rating,desc"

In [ ]:
resp = get(url)
resp.status_code

200

In [ ]:
imdb = Soup(resp.text)

In [ ]:
imdb.find("h3", {'class': 'lister-item-header'}, mode='first').strip()

'1. The Shawshank Redemption (1994)'

In [ ]:
titles = imdb.find("h3", {'class': 'lister-item-header'})

clean_titles = [title.strip() for title in titles]

# for title in titles:
#     clean_titles.append(title.strip())

print(clean_titles)

['1. The Shawshank Redemption (1994)', '2. The Godfather (1972)', '3. The Dark Knight (2008)', '4. The Godfather Part II (1974)', "5. Schindler's List (1993)", '6. 12 Angry Men (1957)', '7. The Lord of the Rings: The Return of the King (2003)', '8. Pulp Fiction (1994)', '9. The Lord of the Rings: The Fellowship of the Ring (2001)', '10. Inception (2010)', '11. Fight Club (1999)', '12. Forrest Gump (1994)', '13. The Lord of the Rings: The Two Towers (2002)', '14. The Good, the Bad and the Ugly (1966)', '15. Goodfellas (1990)', "16. One Flew Over the Cuckoo's Nest (1975)", '17. The Matrix (1999)', '18. Star Wars: Episode V - The Empire Strikes Back (1980)', '19. Interstellar (2014)', '20. The Silence of the Lambs (1991)', '21. The Green Mile (1999)', '22. Se7en (1995)', '23. Star Wars (1977)', '24. Terminator 2: Judgment Day (1991)', '25. Spirited Away (2001)', '26. Saving Private Ryan (1998)', '27. City of God (2002)', '28. Life Is Beautiful (1997)', "29. It's a Wonderful Life (1946)", 

In [ ]:
ratings = imdb.find("div", {'class': 'ratings-imdb-rating'})
ratings = [float(rating.strip()) for rating in ratings]

print(ratings)

[9.3, 9.2, 9.0, 9.0, 9.0, 9.0, 9.0, 8.9, 8.8, 8.8, 8.8, 8.8, 8.8, 8.8, 8.7, 8.7, 8.7, 8.7, 8.6, 8.6, 8.6, 8.6, 8.6, 8.6, 8.6, 8.6, 8.6, 8.6, 8.6, 8.6, 8.6, 8.5, 8.5, 8.5, 8.5, 8.5, 8.5, 8.5, 8.5, 8.5, 8.5, 8.5, 8.5, 8.5, 8.5, 8.5, 8.5, 8.5, 8.5, 8.5]


In [ ]:
import pandas as pd 
imdb_movies = pd.DataFrame({
    "title": clean_titles,
    "rating": ratings
})

imdb_movies.head(10)

title  rating
0                 1. The Shawshank Redemption (1994)     9.3
1                            2. The Godfather (1972)     9.2
2                          3. The Dark Knight (2008)     9.0
3                    4. The Godfather Part II (1974)     9.0
4                         5. Schindler's List (1993)     9.0
5                             6. 12 Angry Men (1957)     9.0
6  7. The Lord of the Rings: The Return of the Ki...     9.0
7                             8. Pulp Fiction (1994)     8.9
8  9. The Lord of the Rings: The Fellowship of th...     8.8
9                               10. Inception (2010)     8.8

## **Basic sklearn ML**